spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pda
    username: postgres
    password: "12345678"

app:
  scheduler-enabled: false
  seed:
    enabled: true
    password: "DemoPassword123!"
